#!/bin/sh

if [ "$MIC_RUN" != "" ]; then
	echo "ssu-update-repos - returning FAIL to postpone oneshot to first boot"
	exit 1
fi

touch /usr/share/ssu/board-mappings.d/*.ini 2>/dev/null
/usr/bin/ssu updaterepos
